services:
  - type: web
    name: workwave-coast-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
